# mongo Field
FIELD_ID = "_id"

# mongo meta const
META_FIELDS = "fields"
META_STRICT = "strict"
META_UNIQUE = "unique"
META_INDEXES = "indexes"
META_ABSTRACT = "abstract"
META_COLLECTION = "collection"
META_INDEX_BACKGROUND = "index_background"
META_AUTO_CREATE_INDEX = "auto_create_index"
META_ALLOW_INHERITANCE = "allow_inheritance"

#  mongo filter const
MONGO_IN = "$in"
MONGO_NE = "$ne"  # MONGO_NotEqual
MONGO_GT = "$gt"
MONGO_LT = "$lt"
MONGO_OR = "$or"
MONGO_AND = "$and"
MONGO_LTE = "$lte"
MONGO_GTE = "$gte"
MONGO_SUM = "$sum"
MONGO_MAX = "$max"
MONGO_MIN = "$min"
MONGO_AVG = "$avg"
MONGO_INC = "$inc"
MONGO_NIN = "$nin"
MONGO_SET = "$set"
MONGO_PUSH = "$push"
MONGO_EACH = "$each"
MONGO_SORT = "$sort"
MONGO_SKIP = "$skip"
MONGO_SIZE = "$size"
MONGO_PULL = "$pull"
MONGO_FIRST = "$first"
MONGO_LIMIT = "$limit"
MONGO_UNSET = "$unset"
MONGO_REGEX = "$regex"
MONGO_COUNT = "$count"
MONGO_MATCH = "$match"
MONGO_GROUP = "$group"
MONGO_ATS = "$addToSet"
MONGO_EM = "$elemMatch"
MONGO_EXISTS = "$exists"
MONGO_UNWIND = "$unwind"
MONGO_PROJECT = "$project"
MONGO_OPTION = "$options"
MONGO_CONTACT = "$concatArrays"
